@init.sql 
@env.sql 
@f500/application/set_environment.sql 
@f500/application/delete_application.sql 
@f500/application/ui_types.sql 
@f500/application/create_application.sql 
@f500/application/shared_components/navigation/lists.sql 
@f500/application/shared_components/files.sql 
@f500/application/plugin_settings.sql 
@f500/application/shared_components/security/authorizations.sql 
@f500/application/shared_components/navigation/navigation_bar.sql 
@f500/application/shared_components/logic/application_processes.sql 
@f500/application/shared_components/logic/application_items.sql 
@f500/application/shared_components/logic/application_computations.sql 
@f500/application/shared_components/navigation/tabs/standard.sql 
@f500/application/shared_components/navigation/tabs/parent.sql 
@f500/application/shared_components/user_interface/lovs.sql 
@f500/application/shared_components/navigation/trees.sql 
@f500/application/pages/page_groups.sql 
@f500/application/shared_components/navigation/breadcrumbs/breadcrumb.sql 
@f500/application/shared_components/user_interface/templates/page.sql 
@f500/application/shared_components/user_interface/templates/button.sql 
@f500/application/shared_components/user_interface/templates/region.sql 
@f500/application/shared_components/user_interface/templates/list.sql 
@f500/application/shared_components/user_interface/templates/report.sql 
@f500/application/shared_components/user_interface/templates/label.sql 
@f500/application/shared_components/user_interface/templates/breadcrumb.sql 
@f500/application/shared_components/user_interface/templates/popuplov.sql 
@f500/application/shared_components/user_interface/templates/calendar.sql 
@f500/application/shared_components/user_interface/themes.sql 
@f500/application/shared_components/user_interface/theme_style.sql 
@f500/application/shared_components/user_interface/theme_files.sql 
@f500/application/shared_components/user_interface/theme_display_points.sql 
@f500/application/shared_components/user_interface/template_opt_groups.sql 
@f500/application/shared_components/user_interface/template_options.sql 
@f500/application/shared_components/logic/build_options.sql 
@f500/application/shared_components/globalization/language.sql 
@f500/application/shared_components/globalization/messages.sql 
@f500/application/shared_components/globalization/dyntranslations.sql 
@f500/application/shared_components/user_interface/shortcuts.sql 
@f500/application/shared_components/security/authentications.sql 
@f500/application/user_interfaces.sql 
@f500/application/user_interfaces/combined_files.sql 
@f500/application/pages/page_00001.sql 
@f500/application/pages/page_00101.sql 
@f500/application/end_environment.sql 
